# -*- coding: utf-8 -*-
"""My-Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ow2d3rkxSN2huZ9OTBn54WnX_qp4yO9

# **My First Colab Notebook**

## **Load dataset**

### Here, I will be loading the Delaney solubility dataset

source: [Data Professor](https://https://colab.research.google.com/drive/17Ow2d3rkxSN2huZ9OTBn54WnX_qp4yO9#scrollTo=1W1eYyC3OYku&line=1&uniqifier=1)r Github
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/delaney_solubility_with_descriptors.csv")
df

